### PR TITLE
added page_load script where we have sleep(..)

### PR DESCRIPTION
**Pull request by oleg-andreyev**
Selenium2Driver has an ability to configure timeout (pageLoad, script, implicit)
By adding this simple script, we can test pageLoad (it was implemented in https://github.com/minkphp/MinkSelenium2Driver/pull/304)

### CODE REVIEW

**Comment by oleg-andreyev** [comment]
ping @aik099 @stof

**Comment by aik099** [comment]
Is this needed, considering, that referenced PR is closed?

**Comment by oleg-andreyev** [comment]
@aik099 it still useful and could be implemented in all the drivers.

**Comment by aik099** [comment]
No harm in merging a test fixture. Merging, thanks @oleg-andreyev .

**Pull request merged**
