### PR TITLE
Fix: don't pass an int to `Session::setCookie()` as it expects only s…

### PR DESCRIPTION
**Pull request by Lctrs**
…tring

### CODE REVIEW

**Comment by aik099** [comment]
Can you please show failing build on Travis CI, that demonstrates that error you've fixed?

**Comment by stof** [comment]
@aik099 given we don't have strict typehints yet, I don't think there is a build failure. But this is actually breaking the contract of the method, which says it accept strings (see https://github.com/minkphp/Mink/blob/a534fe7dac9525e8e10ca68e737c3d7e5058ec83/src/Session.php#L207).
I suspect that this was caught by some static analysis tool.

**Comment by Lctrs** [comment]
@stof Thank you. I was just about to write that. :smile: 

And you're right, `PHPStan` is not happy about it in my implementation, because I have to always cast the `$value` to a string, and it complais that casting a `string` to a `string` is useless.

**Comment by aik099** [comment]
Thanks @Lctrs , merging.

**Pull request merged**
