### PR TITLE
Fix basic auth test: use assertContainsString

### PR DESCRIPTION
**Pull request by cweiske**
Related: https://github.com/minkphp/driver-testsuite/pull/15

### CODE REVIEW

**Review by aik099 — CHANGES_REQUESTED** [review]
You've only completed 1 step out of 3 listed in https://github.com/minkphp/driver-testsuite/pull/15#issuecomment-986749705 .

**Comment by cweiske** [comment]
Because that file already uses the assertContainsString method. No need for me to do it again.

**Comment by aik099** [comment]
> haven't used polyfill trait for older PHPUnit versions, which will result in the Fatal Error on some PHPUnit versions

I see now. Thank you.

> you've used the `assertContainsString` method (not sure if it exists) instead of `assertStringContainsString`, which will result in the Fatal Error all the time

@cweiske , Still the issue.

**Comment by cweiske** [comment]
Oh, sorry. Fixed now.

**Comment by aik099** [comment]
Merging, thanks @cweiske .

**Pull request merged**
