### PR TITLE
Test basic auth (username+password) in URLs

### PR DESCRIPTION
**Pull request by cweiske**

### CODE REVIEW

**Comment by stof** [comment]
@aik099 only after the merge

**Comment by stof** [comment]
Which of the existing drivers already support that, and which one will need a patch ?

**Comment by cweiske** [comment]
- selenium2 does (I wrote so in https://github.com/minkphp/MinkGoutteDriver/issues/76)
- goutte does not

I started this PR here because @aik099 asked in https://github.com/minkphp/MinkGoutteDriver/pull/77 to provide this request so that we'd see which drivers currently support it.

**Comment by stof** [comment]
@aik099 once merged, yes.

**Comment by cweiske** [comment]
Will this go any further? Otherwise I'll close this PR and delete my repository.

**Comment by aik099** [comment]
Merging, thanks @cweiske .

**Comment by aik099** [comment]
@cweiske ,

Ah, now, once tests are executed I can clearly see, that they fail with newer PHPUnit versions.

Next steps:

1. import `Yoast\PHPUnitPolyfills\Polyfills\AssertStringContains` class into relevant test case file
2. add `use AssertStringContains` in that test case file
3. use `assertStringContainsString` instead of `assertContains`

**Comment by cweiske** [comment]
@aik099 done

**Comment by aik099** [comment]
Nice, the Zombie and BrowserKit drivers support basic auth in URL out of the box.

**Comment by stof** [comment]
@cweiske This test fails in the Selenium2Driver CI, probably due to not isolating tests enough

**Pull request merged**
