### PR TITLE
Test drop onto itself and hide when dragging

### PR DESCRIPTION
**Pull request by mvorisek**
needed for https://github.com/minkphp/MinkSelenium2Driver/pull/359

discussed in https://github.com/minkphp/MinkSelenium2Driver/pull/359#issuecomment-1280877930

### CODE REVIEW

**Comment by mvorisek** [comment]
test is correct and working

In Selenium 2.53.1 (latest 2.x) the test does not pass, for some reasons, button up event is not fired.

see 38c6ef7a7c705b47c5dc4165973ab2bbda4b2934 debug output:

```
Drop here, mouseover, mouseover, mouseover, mousemove, mousemove, mousemove, mousedown, mousedown, mousedown, mouseout, mouseout, mouseout, mouseover, mouseover, mouseover, mouseover
```

In Selenium 3.x it passes.

```
Drop here, mouseout, mouseover, ..., mouseup, Dropped small!, click, click, dblclick, dblclick, mouseout, mouseout, mouseout, mouseout, mouseover, mouseover, mouseover
```

Selenium 2.53.1 is very old and the test should be skipped in https://github.com/minkphp/MinkSelenium2Driver/pull/359 and then tested in https://github.com/minkphp/MinkSelenium2Driver/pull/354

**Comment by mvorisek** [comment]
@stof please merge this test as requested in https://github.com/minkphp/MinkSelenium2Driver/pull/359#issuecomment-1280877930

test can be tested locally by clicking the smaller box - notice the drag and drop works even without any mouse move and also when you hold the mouse, the box is not visible

image

I will then take care of skipping the test for Selenium 2.53.1 and testing with 3.x.

**Comment by mvorisek** [comment]
@stof let's please merge this test and then the fix PR.

**Comment by mvorisek** [comment]
@stof this is the test you requested in https://github.com/minkphp/MinkSelenium2Driver/pull/359#issuecomment-1280877930, can you please review it and merge?

**Comment by mvorisek** [comment]
@stof can you please merge this test?

**Comment by mvorisek** [comment]
Hi @stof, can this test be merged, please?

**Comment by mvorisek** [comment]
@aik099 might I ask you for a review?

**Review by stof — APPROVED** [review]

**Pull request merged**
